### ISSUE TITLE
crash when I dropped a glow barries

### ISSUE THREAD

**Issue by EGOIST1372** [stashymane/extra-sounds#62]
Minecraft: 1.19
Mod: 2.3.1 for 1.19

## Details
crash when I dropped a glow barries on ground ;-;

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 6/16/22, 2:14 AM
Description: Unexpected error

java.util.ConcurrentModificationException
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at net.minecraft.client.sound.SoundSystem.tick(SoundSystem:276)
	at net.minecraft.client.sound.SoundSystem.tick(SoundSystem:238)
	at net.minecraft.client.sound.SoundManager.tick(SoundManager:249)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1823)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
	at net.minecraft.class_1140.method_4857(class_1140.java:276)
	at net.minecraft.class_1140.method_20185(class_1140.java:238)
	at net.minecraft.class_1144.method_18670(class_1144.java:249)

-- Affected level --
Details:
	All players: 1 total; [class_746['EGOIST23'/131, l='ClientLevel', x=112.89, y=19.00, z=-89.30]]
	Chunk stats: 1024, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,64,-192), Section: (at 0,0,0 in 9,4,-12; chunk contains blocks 144,-64,-192 to 159,319,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1674643 game time, 298479 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 22
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_1.19.zip, loadmyresources.hiddenpack, minecraft/vanilla_tweaks_smaller_utilities_compatibility, cullleaves/smartleaves, continuity/glass_pane_culling_fix, continuity/default, illuminations/pixelaccurate, illuminations/lowerres, VIllagerAndOthersCloakFix.zip, Eating.Animation.Smaller.Utilities.Compatibility.zip, rope-ladders-with-vines.zip, SpawnEgg3D-1.19.zip, Obscuria's+Stylized+Potions+(1.18).zip, Better_Chickens_v1.2.zip, Better+sheep+-+Mrblueyeti.zip, Butterflies+-+Mrblueyeti.zip, Boss+Bars++1.18+Update.zip, Desert_Bloom-v1.0.2.zip, EclecticTrove-noconfig-1.18.1-1.1.0.zip, EmbellishedStone-1.18-1.0.0.zip, Luminous1.3.zip, itemframes-e700.zip, Classic+Emissives+.zip, Essential (fabric_1.19).jar

**Comment by stashymane** [comment]
[Please try downloading this build](https://github.com/stashymane/extra-sounds/actions/runs/2505920321), the issue should mostly be fixed, though there is one more place I need to work around.

**Comment by EGOIST1372** [comment]
yeah with the new build it doesn't crash with glow barries
thanks <3

**Comment by stashymane** [comment]
By the way, did the crash happen consistently or was it a one-off? Normally, dropping items should crash under very specific circumstances, so I'm not sure whether something else caused it.

**Comment by EGOIST1372** [comment]
After it crashed I did not try it again to see if it was consistent or not. but at that time I was trying some emissive resource packs but IDK

**Comment by EGOIST1372** [comment]
@stashymane this pack I was testing
https://www.curseforge.com/minecraft/texture-packs/classic-emissives

**Comment by EGOIST1372** [comment]
with the new build and that resource pack dropping glow barries doesn't crash anymore. just tested it

**Comment by EGOIST1372** [comment]
@stashymane btw I didn't see any new release for fixing this issue in curseforge. I still use [this build](https://github.com/stashymane/extra-sounds/actions/runs/2505920321) that you gave me but what about other users?
