### ISSUE TITLE
1.19.3 Support | Crash on Startup

### ISSUE THREAD

**Issue by Owehttamy** [stashymane/extra-sounds#92]
Minecraft: 1.19.3 Fabric
Mod: Extra sounds(?)

## Details
Can't run Extra Sounds on Fabric 1.19.3, crash log below:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'extrasounds'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_3414.<init>(net.minecraft.class_2960)'
	at dev.stashy.extrasounds.sounds.SoundRegistry.register(SoundRegistry.java:12)
	at dev.stashy.extrasounds.sounds.SoundRegistry.register(SoundRegistry.java:28)
	at dev.stashy.extrasounds.sounds.Categories.<clinit>(Categories.java:7)
	at dev.stashy.extrasounds.ExtraSounds.onInitializeClient(ExtraSounds.java:26)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.755 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.900 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.900 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.755 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		antimalware_provider64.dll:AMSI provider :
```

**Comment by Owehttamy** [comment]
I updated the crash report, as other mods I used were having issues, adding red herrings.
The report now reflects what occurs when using the current latest Fabric launcher (0.14.12) and API (0.69.1) with only Extra Sounds; there are no outside conflicts.

**Comment by lonefelidae16** [comment]
Same here. I found that Minecraft has a lot of changes between 1.19.2 and 1.19.3.

I’ve written a patch that make this mod compatible with MC1.19.3, but there is the v3 branch on this repo. It’s not a good idea to create a new PR, as I think the default (v2) branch would be marked as end-of-life at some point. So, I thought I would leave this comment while I’m here. ~[Ported branch is available on my repo](https://github.com/lonefelidae16/extra-sounds/tree/port/mc1.19.3).~
Edit: No longer maintained.

On the other hand, this mod has a dependency with SoundCategories, and that also needs to be updated to 1.19.3 compatible. ~[You can find it on my fork](https://github.com/lonefelidae16/sound-categories/tree/port/mc1.19.3).~
Edit: No longer available.

They are able to run on MC1.19.3. If you interested in, and great knowledge of Gradle and JDK, you can try to build.

1. Build and Make the binary of the **SoundCategories** project. Can be located at `build/libs/soundcategories-[version]+[MCversion].jar`.
1. Place it into ExtraSounds’ `run/` directory.
1. Build and Make the binary of the **ExtraSounds** project. Can be located at `build/libs/extrasounds-[version]+[MCversion].jar`.
1. Place two jars into `mods/` directory of your Minecraft Game Directory.
1. Launch your Minecraft 1.19.3 instance and check there are no errors.

----

**For Non Developers**

If you just want to use ExtraSounds 1.19.3, it is available on my maven. But please note, it’s *unofficial* build and you use it *entirely at your own risk*.

~https://artifactory.kow08absty.com/ui/native/fabricmc/dev/stashy/extra-sounds/2.3.1+1.19.3~lonefelidae16-SNAPSHOT/extra-sounds-2.3.1+1.19.3~lonefelidae16-20230111.044325-1.jar~

~https://artifactory.kow08absty.com/artifactory/fabricmc/dev/stashy/extra-sounds/2.3.1%2B1.19.3~lonefelidae16-SNAPSHOT/extra-sounds-2.3.1%2B1.19.3~lonefelidae16-20230111.075334-2.jar~
edit: It’s my mistake. The branch was not up to date.

https://artifactory.kow08absty.com/artifactory/fabricmc/dev/stashy/extra-sounds/2.3.1%2B1.19.3~lonefelidae16-build.4/extra-sounds-2.3.1%2B1.19.3~lonefelidae16-build.4.jar
edit: This is the final release for 1.19.3. I will provide ongoing support for 1.19.4 or newer. Please visit my wiki. https://github.com/lonefelidae16/extra-sounds/wiki

----

**Changes**

For more details, please check my commit log.

* set dependencies as Minecraft 1.19.3 compatible.
* fix double-sounds when playing on Singleplayer world.
* overhaul InventoryScreen sounds.
* fix no sounds when picking an item (default: Mouse Wheel Click) in Survival mode.
* add SwapWithOffhand sound (default: F key).
* update Drop sound (default: Q key).
* add KeyboardTyping sound.
* update handling the cache in `SoundPackLoader`.
* add Bundle sound (Experimental in 1.19.3).
* and some minor fixes...

**Comment by stashymane** [comment]
@lonefelidae16 v3 is still pretty far away, I'm keeping v2 on maintenance until it's released - you can submit PRs to both projects if you wish, though I would very much appreciate splitting changes into separate PRs (e.g. necessary for 1.19.3, additional fixes, etc). Thanks for your contribution in advance :)

**Comment by lonefelidae16** [comment]
@stashymane Hi, thank you for your comment. I see v3 is not coming for now.

However... I’ve crammed a lot of changes into one commit, so I’m going to break it down and separate it into ”Porting”, ”Fix” and ”Enhancement”. When I’m ready, I’ll create new PRs for both projects. It’ll take some time.

**Comment by BlueSky-fur** [comment]
> Same here. I found that Minecraft has a lot of changes between 1.19.2 and 1.19.3.
> 
> I’ve written a patch that make this mod compatible with MC1.19.3, but there is the v3 branch on this repo. It’s not a good idea to create a new PR, as I think the default (v2) branch would be marked as end-of-life at some point. So, I thought I would leave this comment while I’m here. ~[Ported branch is available on my repo](https://github.com/lonefelidae16/extra-sounds/tree/port/mc1.19.3).~ Edit: No longer maintained.
> 
> On the other hand, this mod has a dependency with SoundCategories, and that also needs to be updated to 1.19.3 compatible. ~[You can find it on my fork](https://github.com/lonefelidae16/sound-categories/tree/port/mc1.19.3).~ Edit: No longer available.
> 
> They are able to run on MC1.19.3. If you interested in, and great knowledge of Gradle and JDK, you can try to build.
> 
> 1. Build and Make the binary of the **SoundCategories** project. Can be located at `build/libs/soundcategories-[version]+[MCversion].jar`.
> 2. Place it into ExtraSounds’ `run/` directory.
> 3. Build and Make the binary of the **ExtraSounds** project. Can be located at `build/libs/extrasounds-[version]+[MCversion].jar`.
> 4. Place two jars into `mods/` directory of your Minecraft Game Directory.
> 5. Launch your Minecraft 1.19.3 instance and check there are no errors.
> 
> **For Non Developers**
> 
> If you just want to use ExtraSounds 1.19.3, it is available on my maven. But please note, it’s _unofficial_ build and you use it _entirely at your own risk_.
> 
> ~https://artifactory.kow08absty.com/ui/native/fabricmc/dev/stashy/extra-sounds/2.3.1+1.19.3~lonefelidae16-SNAPSHOT/extra-sounds-2.3.1+1.19.3~lonefelidae16-20230111.044325-1.jar~
> 
> ~https://artifactory.kow08absty.com/artifactory/fabricmc/dev/stashy/extra-sounds/2.3.1%2B1.19.3~lonefelidae16-SNAPSHOT/extra-sounds-2.3.1%2B1.19.3~lonefelidae16-20230111.075334-2.jar~ edit: It’s my mistake. The branch was not up to date.
> 
> https://artifactory.kow08absty.com/artifactory/fabricmc/dev/stashy/extra-sounds/2.3.1%2B1.19.3~lonefelidae16-build.4/extra-sounds-2.3.1%2B1.19.3~lonefelidae16-build.4.jar edit: This is the final release for 1.19.3. I will provide ongoing support for 1.19.4 or newer. Please visit my wiki. https://github.com/lonefelidae16/extra-sounds/wiki
> 
> **Changes**
> 
> For more details, please check my commit log.
> 
> * set dependencies as Minecraft 1.19.3 compatible.
> * fix double-sounds when playing on Singleplayer world.
> * overhaul InventoryScreen sounds.
> * fix no sounds when picking an item (default: Mouse Wheel Click) in Survival mode.
> * add SwapWithOffhand sound (default: F key).
> * update Drop sound (default: Q key).
> * add KeyboardTyping sound.
> * update handling the cache in `SoundPackLoader`.
> * add Bundle sound (Experimental in 1.19.3).
> * and some minor fixes...


Tested with 1.19.4 works flawlessly! thanks a lot!
Im glad it works fine, i've got so used to this mod that playing without it alway felt.. not right xD
